spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jdbc:
        time_zone: Africa/Lagos

  jackson:
    time-zone: Africa/Lagos

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
    com.dss.loan_approval: INFO

server:
  port: ${PORT:8080}

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

app:
  super:
    password: ${APP_SUPER_PASSWORD}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
